### ISSUE TITLE
Export to .PNG feature

### ISSUE THREAD

**Issue by crpietschmann** [lishu/vscode-svg2#1]
Please add an "Export" feature that allows you to save the SVG image to a .PNG file. A useful feature of exporting would be to specify the pixel width of the final image so you can specify the size of the image once it's exported. Also, a "copy to clipboard" feature might be useful along with this as well.

This would be really useful when needing to convert SVG images to PNG's. There are a few use cases for this one, but one that I do a lot is copy .SVG images to import into PowerPoint, but PowerPoint doesn't natively support SVG so they need to be "converted" first.

Thanks for the nice plugin to Visual Studio Code! :)

**Comment by lishu** [comment]
Export has done in this version but clipboard need some experimented.
This is new all rewrite version that not release yet. will be released in the near future.
Thank you for your feedback

**Comment by crpietschmann** [comment]
Oh, nice. Not sure how I didn't see that button in the preview. Anyway, it seems the button doesn't work. When I click the "Export PNG" button nothing happens.

Some details: I am running VS Code 1.37.1 on macOS.

**Comment by crpietschmann** [comment]
I upgraded to VS Code 1.38 and now the "Export PNG" button works only some of the time. Although, you can't specify the size dimensions of the PNG file it exports. It would be super helpful to be able to specify at least the image width in pixel of the PNG to be generated.

Thanks for the super useful plugin!

**Comment by lishu** [comment]
Set width and height in root svg element is easy way control export size.
I will do more check, but if sometime export no working, There is a good chance that SVG has an error.
