### ISSUE TITLE
[Bug] Image tags render in preview but fail to load in render to png

### ISSUE THREAD

**Issue by josh-hemphill** [lishu/vscode-svg2#100]
Just trying to create a simple avatar template that pulls in github user avatar and adds clip path over it. My example works in `<svg>` view but not  in `<img>` view.
The missing image in the render looks like the same one you get when CORS rules prevent it from loading on GitHub markdown pages.
Is the `Render to PNG` able to re-use whatever the current render method is? I assume it's trying to use `<img>`.
```svg
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
	<clipPath id="clipCircle">
		<circle r="100" cx="100" cy="100" />
	</clipPath>
	<image clip-path="url(#clipCircle)" width="200" height="200"
		href="https://avatars.githubusercontent.com/josh-hemphill">
	</image>
	<circle r="97" cx="100" cy="100" stroke="#33cd32" stroke-width="6" fill="none" />
</svg>
```

**Comment by lishu** [comment]
This is Webview limit [csp](https://developers.google.com/web/fundamentals/security/csp/)

If I manually download the image files before displaying it, it will cause the preview window to respond slowly.
It also causes too much disk IO.

I would try to find a better solution.

Thank you for your feedback

**Comment by lishu** [comment]
The new version will has this settings, bug default is `false` for speeds.
![image](https://user-images.githubusercontent.com/1331008/152630479-8cab94d7-d8c1-4baa-b79b-cee650c73c8c.png)

**Comment by josh-hemphill** [comment]
Just realized it doesn't render the same way in the PNG export. Is that fixable?
