### ISSUE TITLE
Scaling factor

### ISSUE THREAD

**Issue by Jihadist** [lishu/vscode-svg2#102]
Does this extension support scaling smaller than 8%? Because I have very big .svg (distance between two points is more than 1 kk). So I need scalling factor 0.1 or 0.01%

**Comment by lishu** [comment]
😱 This is not expected, can you give a simple example file for testing

**Comment by Jihadist** [comment]
Yep
![image](https://user-images.githubusercontent.com/26579016/153214862-c3d39d00-e92f-4b80-86cd-bfb1d4097671.svg)
P.s. Couldn't be rendered correctly in Firefox or Chrome

**Comment by Jihadist** [comment]
Thanx 👍
