### ISSUE TITLE
Syntax highlighting gets confused in JS files

### ISSUE THREAD

**Issue by jl-stellar** [lishu/vscode-svg2#104]
I'm generating some SVG code in a JS file and found an interesting bug. It disappeared as soon as I disabled the SVG exension, so I think this is the right place for it.

It happens after this line of JS code:
`let path = '<g id="symbol"><path d="';`
In my code, what follows is some JS that checks a couple of variables and appends SVG path specifiers to the `path` string. It all works fine. However, the syntax highlighting seems to recognize the starting `d="` and highlights the letters used in SVG path specifiers (a, M, l, etc.):
![weird_highlighting](https://user-images.githubusercontent.com/69909183/159511102-a7f77ae7-02e0-486a-928b-d9456d28dbd1.png)

I could reproduce this issue by creating a new file, setting the language to JavaScript and pasting the code above.

Side note: I'm using [VSCodium](https://vscodium.com/), not the "original" VSCode.

Here's the above code for easier copy&paste:
```js
let path = '<g id="symbol"><path d="';
var x = 'Lorem ipsum dolor sit amet';
// Also works on comments
let end = 'this stays like that until the path is closed with double quotes"';
console.log('Then all is back to normal.');
```

**Comment by lishu** [comment]
It's strange that all the features of this plugin are for `svg` types only and are not designed for mixed document types.

Are you configuration this extension use in `js` ?

**Comment by jl-stellar** [comment]
> Are you configuration this extension use in `js` ?
I'm not sure how to do that, there doesn't seem to be a setting for this in the plugin settings.
However, I did not change any settings of the plugin, so they are all at their default values.

**Comment by lishu** [comment]
For now, you can just turn off `Path Data Highlight` in settings. I will do more test.
![image](https://user-images.githubusercontent.com/1331008/160958559-4c0a5b18-ef12-41c2-9627-224462fa8dcc.png)
