### ISSUE TITLE
How to block zoomed preview while changing code?

### ISSUE THREAD

**Issue by jacekblach** [lishu/vscode-svg2#110]
When the view of SVG file in the previewer is zoomed (e.g. 400%), during changes (e.g. path values), zoom automatically comes back to the 100% view.
Is it possible to block the zoomed view during code changes?

**Comment by jacekblach** [comment]
Thank you very much for your work and for blocking zooming.
I want to ask you for another favor yet. Because it is another issue which can help when working with zoomed preview.
This means, while the SVG file is zoomed position, the view automatically moves to the upper-left corner after every code change. For example, when the view of the SVG file is in the lower-right corner after a code change, the view automatically moves to the top-left corner.
So, is it possible to block the position of the zoomed preview?
I will be grateful for this fixing.

**Comment by lishu** [comment]
Design reasons, center auto size mode is to quickly view the entire graphic, normal mode because of the ruler, grid and other reasons, the upper left corner layout is easier

**Comment by jacekblach** [comment]
Ok. Thank you for your answer and explanation.
I like your extension very much. It is very useful. I am grateful for your work in creating and maintaining it.
In the meantime, I start using your preview for a general view. And for the zoomed view, I use
SVG Previewer - https://marketplace.visualstudio.com/items?itemName=vitaliymaz.vscode-svg-previewer
It is worse than yours, but it stays in the zoomed position I need while changing the code.
