### ISSUE TITLE
"svg.minify.prefixIds": false | still add prefix to IDs

### ISSUE THREAD

**Issue by Tranberry** [lishu/vscode-svg2#117]
### Steps to reproduce

1. Go to settings
2. Set it to: `"svg.minify.prefixIds": false,`
3. Run minify svg
4. all classes and ids have prefix

### Expected behavior
expect minify to not add prefixes to IDs at the least, would be great if it didn't add em to classes either.

**Comment by lishu** [comment]
I had try your steps and results are not what you describe.
Can you get some demo svg files and settings.
