### ISSUE TITLE
No preview functionality and settings aren't working.

### ISSUE THREAD

**Issue by dungle-scrubs** [lishu/vscode-svg2#121]
I'm not sure how to reproduce this.  I've just done a fresh installation of VSCode and installed this extension

- There's no option to preview the SVG in the upper right corner. There doesn't seem to be a way to preview a single SVG.
- Preview all: Exclude doesn't seem to be working, however I can preview all SVGs.  I'm using the default setting of `**/node_modules/**` but all SVGs found within `node_modules` are showing in the preview.
- Preview:Background doesn't change the background color.

Any additional information I can provide?

Cheers

**Comment by lishu** [comment]
Are you using the latest official `vscode`?
