### ISSUE TITLE
how do I change the tabSize?

### ISSUE THREAD

**Issue by thealjey** [lishu/vscode-svg2#13]
how do I change the tabSize to 2 spaces instead of 4?

**Comment by lishu** [comment]
Just try write your settings.json like [This](https://stackoverflow.com/questions/29972396/how-can-i-customize-the-tab-to-space-conversion-factor).

**Comment by lishu** [comment]
Close Reason: Solution given and customer no longer reply

**Comment by thealjey** [comment]
@lishu  that is really not an answer at all
I am not stupid and the tabSize works for literally every file type, except svg
and only with this extension installed
because this extension ships with it's own setting, which I am unable to override
again, ONLY for svg files

**Comment by lishu** [comment]
Indeed, the default tabSize setting was overridden due to feedback from other users earlier.
But you should be able to manually override this setting without any problems.
Open your **settings.json** add a **language target override** like below:
```json
    "[svg]": {
        "editor.tabSize": 2
    }
```

**Comment by lishu** [comment]
Keep feedback and I'd like to know if this solves the problem.

**Comment by thealjey** [comment]
I have tried that after seeing this solution mentioned on stackoverflow.
I copy pasted their solution to avoid typos
it didn't work

this time I noticed in VSCode settings the the cog menu next to the "[svg]" setting has a "Copy Setting as JSON" item
after copying and editing that, it worked all of a sudden
I have no idea why it didn't work the first time

still, it's really strange to me that someone would ever need a different tabSize for different file types
in my opinion the global setting should work for all of them
and the setting shipped with this extension breaks that expectation

so, it's all good now and the issue can be closed
but, this can potentially be very confusing for some people, imho
