### ISSUE TITLE
How to open PNG export preview

### ISSUE THREAD

**Issue by janstieler** [lishu/vscode-svg2#136]
HI,
how can I open the png export window?
I see no Icon in the right upper corner like in your readme.

Cheers

**Comment by lishu** [comment]
![image](https://user-images.githubusercontent.com/1331008/214470878-0509d85e-120a-42d6-b88f-b019c3ffd49a.png)

At last item at preview view.

**Comment by janstieler** [comment]
Thanks, but in first I need to open this previewwindow. 
Eventual it is overwritten by svgpreview. I will take a look.

**Comment by lishu** [comment]
Because export is base html canvas, so need a webview do that.

**Comment by lishu** [comment]
There are three ways to open the preview window:
1. Select 'Preview SVG' in the context menu of the svg file in Explorer.
![image](https://user-images.githubusercontent.com/1331008/214475932-46b32d5f-f975-42f7-92ab-d8f708c22155.png)
2. Click the preview icon in the upper-right corner of the editor.
![image](https://user-images.githubusercontent.com/1331008/214475983-23d3a741-8424-4226-8235-9221d4f4babe.png)
3. Select 'Preview SVG' ('svg.showSvg') in the command panel.
![image](https://user-images.githubusercontent.com/1331008/214476034-52f99cbc-a583-4b40-a16e-4d1d20bac2fd.png)
