### ISSUE TITLE
Locally sourced `<image>` objects don't render in preview

### ISSUE THREAD

**Issue by craxal** [lishu/vscode-svg2#138]
If I add an image element to an SVG file:

```svg
<image width="100" height="100" xlink:href="LocalImage.jpg">
</image>
```
The preview does not render the image. But I know it's correct, because web browsers render the image correctly.

**Comment by lishu** [comment]
Preview is limited with vscode webview security and cannot load your local files directly.

The relevant conversion processing will be implemented later.
