### ISSUE TITLE
No preview functionality

### ISSUE THREAD

**Issue by jp-lg** [lishu/vscode-svg2#141]
There doesn't appear to be any option to show a preview - it's not explained in the documentation how to show it - the GIF isn't really sufficient. It is possible that there is maybe a conflicting VSCode setting.

**Comment by lishu** [comment]
Make sure the file type in the bottom right corner reads 'SVG'.

Click the preview icon in the upper-right corner of the active editor.

**Comment by alleluya-young** [comment]
> 

hi, 英语不太好 说中文了 预览svg这个功能我记得之前右键的时候是有的 今天用的时候发现没了? 请问现在只能通过右上角的预览按钮或者ctrl+shift+p 搜svg.showSvg才能预览么?(在不自己绑定热键的情况下)

**Comment by jp-lg** [comment]
Thanks, got it sorted - I had the vscode status bar hidden, and when I unhid it it showed that I needed to configure the file association for svgs. All working now.

**Comment by lishu** [comment]
> > 
> 
> hi, 英语不太好 说中文了 预览svg这个功能我记得之前右键的时候是有的 今天用的时候发现没了? 请问现在只能通过右上角的预览按钮或者ctrl+shift+p 搜svg.showSvg才能预览么?(在不自己绑定热键的情况下)

我这里没有问题啊，有其它信息可以参考吗？
![image](https://user-images.githubusercontent.com/1331008/224485632-4cc727a9-3b0c-4506-ac90-698471717e64.png)
![image](https://user-images.githubusercontent.com/1331008/224485655-a313c615-3b3d-41e2-b9c3-a4bedf8e1dc4.png)

可以试试先打开一次 svg 文件。看看是不是因为插件没有初始化

**Comment by alleluya-young** [comment]
> > > 
> > 
> > 
> > hi, 英语不太好 说中文了 预览svg这个功能我记得之前右键的时候是有的 今天用的时候发现没了? 请问现在只能通过右上角的预览按钮或者ctrl+shift+p 搜svg.showSvg才能预览么?(在不自己绑定热键的情况下)
> 
> 我这里没有问题啊，有其它信息可以参考吗？ ![image](https://user-images.githubusercontent.com/1331008/224485632-4cc727a9-3b0c-4506-ac90-698471717e64.png) ![image](https://user-images.githubusercontent.com/1331008/224485655-a313c615-3b3d-41e2-b9c3-a4bedf8e1dc4.png)
> 
> 可以试试先打开一次 svg 文件。看看是不是因为插件没有初始化

噢噢 这里右键是有预览的 我记得之前在svg文件内右键也能看到的 可能是我记错了?
![image](https://user-images.githubusercontent.com/31433884/224586202-105498df-3b81-41ab-9883-d7ecbff295ac.png)
