### ISSUE TITLE
Can't export SVG to PNG!! "Export PNG Fail, SVG may need to be corrected."

### ISSUE THREAD

**Issue by piwawa** [lishu/vscode-svg2#144]
![image](https://user-images.githubusercontent.com/46926496/224600377-f883fd67-c01f-45ee-bcd7-d1a3939c5d4f.png)
![屏幕截图 2023-03-13 111938](https://user-images.githubusercontent.com/46926496/224600645-da249219-b95a-4d0b-a888-185e386c36f3.jpg)

**Comment by lishu** [comment]
Your svg root element lost `xmlns="http://www.w3.org/2000/svg"`.

**Comment by lishu** [comment]
Your svg root element lost `xmlns="http://www.w3.org/2000/svg"`.

**Comment by piwawa** [comment]
> Your svg root element lost `xmlns="http://www.w3.org/2000/svg"`.

What does it mean? I also don't know where to add it.

**Comment by lishu** [comment]
The first `svg` element must have `xmlns="http://www.w3.org/2000/svg"`.

You can see any .svg file will has it.
