### ISSUE TITLE
Please add external CSS file reference support

### ISSUE THREAD

**Issue by SetTrend** [lishu/vscode-svg2#147]
Currently, external CSS files referenced by something this:

```svg
<svg xmlns="http://www.w3.org/2000/svg">
  <style>
    @import url('./my.css');
  </style>
</svg>
```
… are not supported. Preview doesn't show the styled result.

Please add support.

**Comment by lishu** [comment]
The new version has been implemented, but it is important to know that it cannot be updated in real time, and the CSS selector of the toolbar can be used to update in real time.

**Comment by SetTrend** [comment]
@lishu:

This is strange. So a manual refresh is necessary even when opening a fresh file?

Doesn't work:

![SVG extension fails](https://user-images.githubusercontent.com/9283914/226118612-1a791ef0-136b-4271-821c-b7a967f45f59.gif)
