### ISSUE TITLE
Option to prevent create `.vscode\settings.json`

### ISSUE THREAD

**Issue by kanlukasz** [lishu/vscode-svg2#15]
Hello,

Every time I open the preview of the `svg` file and change the background in the preview, your extension creates the directory` .vscode` with `settings.json` in my project folder.

Can we prevent this? I don't use any settings from workspace level so i don't need this folder and file.

**Comment by lishu** [comment]
Thank you for your feedback.
However, this requirement does not appear to be required unless more users have this requirement

**Comment by lishu** [comment]
If you only preview a `svg` file, just drag it to your browser is more easier

**Comment by kanlukasz** [comment]
Thank you for your response.

Yes, I know I can use the browser, but I love automation.
Things that can be done in VSCode i would like to do in VSCode

Note that how VSCode works:
VSCode allows users to choose - everyone can use global settings (global settings.json) * or * local settings (.vscode dir in the project).
Many VSCode add-ons do the same. In my opinion this is the best way

This is just my idea / concept that you can consider
Anyway I respect your work and your decisions.
Thank you for your time

**Comment by lishu** [comment]
Most people make images based on the project's primary background color, so storing the background color to the current workspace is a better solution.
But I'll reconsider how to fix your needs.
