### ISSUE TITLE
Warning reports in element SVG attributes

### ISSUE THREAD

**Issue by ronaldosc** [lishu/vscode-svg2#154]
There's a misundestood on provide errors for camelcase attributes in SVG tagname:  

![image](https://user-images.githubusercontent.com/37854996/232343606-2f1bfa49-d799-4be6-a126-ccbfacf9e1fa.png)
  
The error point to attributes the tagname error for using only lowercase.
  
But as we see in MDN the element attributes support camelcase:  

![image](https://user-images.githubusercontent.com/37854996/232343748-3c859267-4cd0-4cac-b09a-2df3100d60ba.png)

**Comment by lishu** [comment]
This error message comes from other third-party extensions, and VSCode displays information from multiple extensions together

**Comment by ronaldosc** [comment]
I noted this is a warning from HTML, not a pure svg file.

**Comment by lishu** [comment]
You can see what's missing by disabling the SVG extension, which is what the extension provides, and the rest is naturally not.

**Comment by ronaldosc** [comment]
@lishu   

Pehaps in extension description you can cite that it wasn't develop for element inline SVG within HTML.

for reforcing that can surges some tipe of warnings in the names used in SVG.
