### ISSUE TITLE
Jump to filter result variable could jump to the wrong result

### ISSUE THREAD

**Issue by BuZZ-dEE** [lishu/vscode-svg2#17]
Jump to filter result variable could jump to the wrong result if there are results with the same name.

[See `in2="cs"` for filter `id="clarendon"`.](https://github.com/BuZZ-dEE/SVGram/blob/master/fegram.svg?short_path=ecaa83f)

**Comment by lishu** [comment]
This short time cannot be optimized because the current lookup is based on the regular, not semantic, and this is a performance performance and completely correct balancing issue.

So If you may, just don't use duplicate IDs
