### ISSUE TITLE
What word should i search in marketplace and then install it ?

### ISSUE THREAD

**Issue by BryanAdamss** [lishu/vscode-svg2#18]
I dont find a way to install it?

I try to search `vscode-svg2` in `vscode marketplace` , but get nothing!

so , how can i install it?😂

**Comment by lishu** [comment]
`SVG` Since the first release in 2017.
First project name vscode-svg and i dont want 'vscode-' in VS Code. so only use svg as name.

**Comment by lishu** [comment]
Full Id is `jock.svg`, In [Marketplace](https://marketplace.visualstudio.com/items?itemName=jock.svg)
If you like this extension, please support it with five stars.

**Comment by BryanAdamss** [comment]
> Full Id is `jock.svg`, In [Marketplace](https://marketplace.visualstudio.com/items?itemName=jock.svg)
> If you like this extension, please support it with five stars.

get it
