### ISSUE TITLE
svg with namespace does not generate preview

### ISSUE THREAD

**Issue by pgundlach** [lishu/vscode-svg2#21]
Consider this document:

```xml
<svg:svg xmlns:svg="http://www.w3.org/2000/svg" version="1.1"
     width="120" height="120">
  <svg:rect x="14" y="23" width="200" height="50" fill="lime"
      stroke="black" />
</svg:svg>
```

As far as I know, this is equivalent to the default namespaced version:

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
     width="120" height="120">
  <rect x="14" y="23" width="200" height="50" fill="lime"
      stroke="black" />
</svg>
```

But the first one does not render anything in the preview window.

v1.1.7

I'd be happy to provide more info if you need it.

**Comment by lishu** [comment]
Preview is Browser Direct Display.
Most users also use SVG in the browser.
Svg with not default namespace maybe the correct document but doesn't show it directly in the browser.
Converting to a displayable XML namespace style will have a greater impact on the stability of the preview feature.

**Comment by pgundlach** [comment]
It works in Safari, but I assume this is an electron issue then. Thank you for your answer, the issue might be close as "wontfix" (ok for me).

**Comment by lishu** [comment]
Try 1.1.8 has new preview mode switch.

**Comment by pgundlach** [comment]
Works fine! Thank you.
