### ISSUE TITLE
Add CSS support for the <style> element

### ISSUE THREAD

**Issue by TimJentzsch** [lishu/vscode-svg2#26]
The `<style>` element should be properly supported, using CSS syntax highlighting.
Currently, the `<style>` content is displayed as plain text:
![CSS display in the style tag](https://user-images.githubusercontent.com/13908946/82487116-315fca80-9ade-11ea-9b5e-d81d0d1d613d.png)
 Furthermore, formating the document deletes parts of the content.

Language embedding should be used to invoke all CSS language features.

The `<style>` reference is available [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style).

**Comment by TimJentzsch** [comment]
The VS Code embedded language documentation is available [here](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages).

**Comment by lishu** [comment]
Base css supported has add to  1.2.0 release.
But this feature will not Further expansion, Complex large styles should be fully supported by using independent style files
