### ISSUE TITLE
[Enhancement idea] Option to open the preview only by right-clicking

### ISSUE THREAD

**Issue by kanlukasz** [lishu/vscode-svg2#27]
Hello,

What do you think about adding the option to open the preview by right-clicking?

I would like to right click and open the preview (**without the source code of the file**)
It will be very very very useful to preview SVG files when you have many files that you want to open

This is the native way viewing JPG files in VSCode

**Comment by lishu** [comment]
Do you mean in **EXPLORER**? It seems that this is the right-click menu controlled by vscode, and I don't think I have the ability to rewrite its behavior.
Currently, `Preview SVG` is the **first item** in the right-click menu, which should not be a big problem.
About view all your SVG in once, This mybe need a new ui to do. 
If that's exactly what you need, please reply.

**Comment by kanlukasz** [comment]
> Do you mean in **EXPLORER**?

Yes

> Currently, `Preview SVG` is the **first item** in the right-click menu, which should not be a big problem.

Ok this is fine for me, but there is one inconvenience - `Preview SVG` show preview  always in one same Tab. Is it possible to change it? 

I mean:
1. After clicking `Preview SVG` -> svg preview is displayed (this is ok)
2. After clicking `Preview SVG` on next file -> this preview is displayed on the same tab, replacing the previous one (it's not ok - it's better if the next tab opens)

**Comment by lishu** [comment]
That's the design goal. **SVG Previewer** will auto show your active/selected SVG document and Live updates.
So i only create one previewer for a clean experience, 
What you need is one-by-one previewer, It takes time to implement.

**Comment by kanlukasz** [comment]
Ok, I understand
I'm just looking for a quick and fast way to preview SVG files in VSCode. That's why I decided to open this issue

**Comment by lishu** [comment]
Some new feature in release 1.3.0 maybe good for this.
Detial see the changelog

**Comment by kanlukasz** [comment]
Couple insights after update

1. The old behavior stopped working. Now it's not possible to preview the next file on the same tab.
Is this intended? I am asking because maybe other users liked it

2. After runing `Preview All SVG` there is an error.
The command can be called correctly the first time, but the second time and every next time an error pops up
![obraz](https://user-images.githubusercontent.com/30685349/83545281-489bb080-a4ff-11ea-9709-c194e6e9029b.png)

#### My environment:
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by lishu** [comment]
1.Old behavior will working if `svg.preview.viewMode` configuration is default `onlyOne`.
2.Will fix it right away.

**Comment by kanlukasz** [comment]
> 
> 
> 1.Old behavior will working if `svg.preview.viewMode` configuration is default `onlyOne`.

Unfortunately not. I have set:
![obraz](https://user-images.githubusercontent.com/30685349/83602928-c26d8180-a573-11ea-9399-cb2c20f90993.png)
but nothing happens when you try to open the next file

Look at GiF screenshot below:
![xxx](https://user-images.githubusercontent.com/30685349/83603516-dfef1b00-a574-11ea-81e8-b5fe4c79a865.gif)

Something is mixed beacuse if is set this to true it working fine
![obraz](https://user-images.githubusercontent.com/30685349/83603602-01500700-a575-11ea-91df-f2e7fa1aa9cf.png)

But this option should affect opening the source with the preview file - now this is not affected

if what I described is too chaotic, let me know and I will make a new issue with a detailed step-by-step description

**Comment by lishu** [comment]
There are more settings in the preview section at the moment, and I'm sorry that some of the combinations of settings I haven't tested, and I'll fix this as soon as possible.
Your instructions are very detailed and professional, thank you for your reply.

**Comment by kanlukasz** [comment]
Thank you, the right-click preview works correctly now
You still have one problem with `svg.preview.autoShow`, but I will make a new ticket about it because here we have too many problems at once

**Comment by kanlukasz** [comment]
Oh, somebody has already reported it - https://github.com/lishu/vscode-svg2/issues/28
