### ISSUE TITLE
Unwanted preview even though 'auto show' is turned off

### ISSUE THREAD

**Issue by Friksel** [lishu/vscode-svg2#28]
Since last versions suddenly when opening a SVG file there's an unwanted (to me) preview opening on the side which wasn't the case before. In VS Code settings --> SVG -->'Preview: Auto Show' is turned off, so I might expect the preview to stay away. It' pretty frustrating to have these previews popup every time while editing SVG's, so a fix to this would be highly appreciated! Or am I missing something here perhaps?
Other than that; thanks for the plugin!

SVG: 1.3.2 (latest)
Vs Code: 1.45.1 (latest)

**Comment by kanlukasz** [comment]
I confirm this issue

Example:
![xxx2](https://user-images.githubusercontent.com/30685349/83640137-00869780-a5ac-11ea-9eef-79eb77f8c804.gif)

**Comment by lishu** [comment]
I'm very sorry for causing this problem, and I'll fix it as soon as possible.

**Comment by Friksel** [comment]
@lishu Thanks for fixing this so quickly! Just installed the new version and that solves the issue! Thanks a lot and have a nice day!
