### ISSUE TITLE
Option to disable syntax highlighting

### ISSUE THREAD

**Issue by misolori** [lishu/vscode-svg2#3]
I love the preview portion of this extension but I really don't want to see syntax highlighting coming from this extension as it doesn't look nice with themes:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/35271042/65447075-a2819d80-ddea-11e9-881e-ff4dcdd10c95.png">

Can you please provide an option to disable this?

**Comment by lishu** [comment]
Set `svg.pathDataHighlight` to `false` can disable path d content highlight.
If you don't like whole，Can you show me what is you like?

**Comment by misolori** [comment]
Thanks, that setting will do it.

**Comment by hisbvdis** [comment]
@lishu , Setup does not work after VS Code restarting
https://youtu.be/RSmEFZX-Pz8

**Comment by hisbvdis** [comment]
@lishu , thanks
