### ISSUE TITLE
Support currentColor

### ISSUE THREAD

**Issue by jtackett-collinear** [lishu/vscode-svg2#30]
There are many SVGs that use the currentColor keyword to use the text color and it would be nice if the viewer could change the color value as well as background.

**Comment by lishu** [comment]
I see what you mean, but when currentColor is actually used, each SVG element has a different color due to css. So a separate currentColor color setting doesn't accurately represent SVG's real display results, and I need to think of a better way.

**Comment by lishu** [comment]
Try new version 'CSS' button(svg mode only), write a css file control all preview svg style.
eg:
```css
svg {
  color: red
}
```

**Comment by ChazUK** [comment]
@lishu how can you add custom CSS for the preview mode?
