### ISSUE TITLE
Format feature does not support <style>.

### ISSUE THREAD

**Issue by andystevenson** [lishu/vscode-svg2#33]
I have deselected
`{
  "svg.minify.inlineStyles": false,
  "svg.minify.minifyStyles": false
}
`

in my user/workspace settings.json and it is ignored. svgo is still inlining and minify the css within the <style>.
I then copied the above settings into the local project settings.json. No change. Still being optimised.

**Comment by lishu** [comment]
I has try change these settings and re-run `Minify SVG` command, I see thing done diff.
Can you provide more information?

**Comment by andystevenson** [comment]
Hi Jock,

Thanks for getting back to me.

I think I have spotted the problem.
If I run Minify SVG from the shift-command-P then you’re right it works.
However I also have 
  "[svg]": {
    "editor.defaultFormatter": "jock.svg",
    "editor.tabSize": 2,
    "editor.formatOnSave": true
  },

In my settings.json file. It is the save that seems to ignore the settings for svgo?

Regards, Andy

**Comment by lishu** [comment]
Format and Minify is not one thing, 
`Format` is make code better readable, 
`Minify` is compress to smaller.

**Comment by lishu** [comment]
These should both in your document context menu to easy access, some other thing override it ?
![2020-07-18 230047](https://user-images.githubusercontent.com/1331008/87855423-d108d000-c94a-11ea-8824-e954868cce02.png)

**Comment by andystevenson** [comment]
Hi Jock,

Yes they are there.

But it seems to be the formatOnSave that is ignoring the settings.json.
formatOnSave seems to only look at the node_module .svgo.yml and not the overrides in settings.json.
  "[svg]": {
    "editor.defaultFormatter": "jock.svg",
    "editor.formatOnSave": true
  },

Regards, Andy

**Comment by andystevenson** [comment]
Hi Jock,

Sorry to be a pain.
Best to show you the example of what I mean.

**Comment by andystevenson** [comment]
Hi … hit send too soon!

I attach 3 files.

before.svg - what I edited and simply want formatting on save.
after.svg - what got saved.
Then diff of the two.

My complete settings.json for svg is.
"[svg]": {
  
    "editor.defaultFormatter": "jock.svg",
    "editor.tabSize": 2,
    "editor.formatOnSave": true
  },
  "svg.minify.inlineStyles": false,
  "svg.minify.minifyStyles": false,
  


Here is the diff.

6,14c6
<     @keyframes cycle{
<       33.3%{visibility:visible}
<       99%{visibility:hidden}}
<       .lit{animation:cycle 9s step-start infinite}
<       .black{stroke:#000}
<       text{font:700 60px sans-serif}
<       .red .lit {animation-delay: -3s;}
<       .yellow .lit {animation-delay: -6s;}
<       .green .lit {animation-delay: 0s;}
---
>     @keyframes cycle{33.3%{visibility:visible}99%{visibility:hidden}}.lit{animation:cycle 9s step-start infinite}.black{stroke:#000}text{font:700 60px sans-serif}
63c55
<       <g class="lit" fill="url(#red-light-on)" visibilty="hidden">
---
>       <g class="lit" fill="url(#red-light-on)" visibilty="hidden" style="animation-delay:-3s">
72c64
<       <g class="lit" fill="url(#yellow-light-on)" visibilty="hidden">
---
>       <g class="lit" fill="url(#yellow-light-on)" visibilty="hidden" style="animation-delay:-6s">
81c73
<       <g class="lit" fill="url(#green-light-on)" visibilty="hidden">
---
>       <g class="lit" fill="url(#green-light-on)" visibilty="hidden" style="animation-delay:0s">

It appears that format on save has minified the <style> and inlined at least part of it, ignoring the svg.minify.inlineStyles: false and svg.minifyStyles:false.

Hope that helps clarify my problem.
Many thanks for all your help.





Regards, Andy

**Comment by andystevenson** [comment]
Hi Jock,

I should also have mentioned if I select Format Document from the menu it does the same thing.

Regards, Andy

**Comment by lishu** [comment]
I am sorry what I never use the `formatOnSave` & `svgo` features myself.
Maybe need some time make it right, Sometime you can try download [svgo](https://github.com/svg/svgo) cli tool for more direct control.
I'll continue to give feedback here when there are improvements.

**Comment by lishu** [comment]
Try new `1.3.6`, I had changed format SVG options.

**Comment by andystevenson** [comment]
Thanks Jock, really appreciate your support.

Regards Andy

**Comment by andystevenson** [comment]
Hi Jock,

Hate to be a pain but formatOnSave is still minifying the style. Inlining is fixed which is great.

6,14c6
<     @keyframes cycle { 
<       33.3%{visibility:visible} 
<       99%{visibility:hidden} } 
<       .lit{animation:cycle 9s step-start infinite} 
<       .black{stroke:#000} 
<       text{font:700 60px sans-serif} 
<       .red .lit {animation-delay: -3s;} 
<       .yellow .lit {animation-delay: -6s;} 
<       .green .lit {animation-delay: 0s;}
---
>     @keyframes cycle { 33.3%{visibility:visible} 99%{visibility:hidden} } .lit{animation:cycle 9s step-start infinite} .black{stroke:#000} text{font:700 60px sans-serif} .red .lit {animation-delay: -3s;} .yellow .lit {animation-delay: -6s;} .green .lit {animation-delay: 0s;}


Regards, Andy

**Comment by lishu** [comment]
I'm sorry, I checked SVGO. not any options can control this action.
SVGO handle style content like text.
This issue can not handle short time.

**Comment by lishu** [comment]
Please try 1.3.7 release.
I had change format support use `vscode-html-service`.
This maybe better for you.

**Comment by lishu** [comment]
Hi @andystevenson , This issue is now closed, and if you think there's a problem, create a new one.

**Comment by andystevenson** [comment]
Jock,

Thanks very much for your support.

Regards Andy
