### ISSUE TITLE
top bar on svg preview covers top of preview

### ISSUE THREAD

**Issue by sometimescasey** [lishu/vscode-svg2#35]
Please see this screenshot for an example...is there a simple config change that I am missing?

(otherwise, thank you for the awesome work!)

![image](https://user-images.githubusercontent.com/16248601/88837739-72f0ae00-d1d0-11ea-98de-f237f8a81962.png)

**Comment by lishu** [comment]
Hey, you've found a legacy problem, and that's what happens when the toolbar wraps. Because this is rare, the problem has not been dealt with. will be processed in the few days.

**Comment by sometimescasey** [comment]
^ Ah thank you for the quick reply! Appreciate it :)
