### ISSUE TITLE
Why cannot find this extension in vscode marketplace?

### ISSUE THREAD

**Issue by CorScorpii** [lishu/vscode-svg2#37]
I was recommended to use this extension to replace SVG Viewer. But I cannot find this extension in VSCode marketplace if I search vscode-svg or svg. Is that something wrong? Or could you update a guide about how to install your extension manually?

**Comment by lishu** [comment]
The `SVG` is just the display name. First in search result.
![批注 2020-08-08 214052](https://user-images.githubusercontent.com/1331008/89711925-e4461300-d9bf-11ea-9807-d599225cec47.png)

**Comment by lishu** [comment]
And a `Visual Studio Marketplace` link button in first line at `README`.
