### ISSUE TITLE
Export PNG Fail, SVG may need to be corrected.

### ISSUE THREAD

**Issue by mastoj** [lishu/vscode-svg2#38]
I'm trying out the drawio plugin for vs code and try to generate a svg that I can use. I have no problem showing the generated svg in the preview, but for some reason I can "Export PNG", it just give the error: `Export PNG Fail, SVG may need to be corrected.`

Is this a known issue or something I can do to resolve it?

**Comment by lishu** [comment]
Try exporting using <IMG> mode, which has different rendering methods than <SVG> modes and typically solves problems such as <SVG> mode and different expected results.

**Comment by mastoj** [comment]
@lishu how do I do that? The way I do it now is `File -> Embed -> Svg`.

**Comment by lishu** [comment]
I'm sorry This mode is can not use from command, You need to operate in the `svg previewer`.

**Comment by blackdahlia** [comment]
Hi,

I'm using this [extension ](https://marketplace.visualstudio.com/items?itemName=jock.svg) (v1.4.13) in Visual Studio Code and got the same error message in the preview mode (I chosed `<svg>`) when exporting PNG:

```code
Export PNG Fail, SVG may need to be corrected.
```

My SVG is:

```svg
<svg viewBox="0 0 1000 500">
  <circle cx="29%" cy="47%" r="155px" stroke="black" stroke-width="10px" stroke-dasharray="835" stroke-dashoffset="-85" fill="none"/>
  <circle cx="43.58%" cy="36.5%" r="5px" fill="black"/>
  <circle cx="42.26%" cy="63.05%" r="5px" fill="balck"/>
  <text x="17%" y="60%" fill="black" font-family="Autoguard" font-size="200">Hello</text>
</svg>
```

When I chose `<img>` and click on the right arrow symbol ("Export PNG") then it looks like nothing happens. I cant see anything in the extension logs.

What is the problem with my SVG?

I tried epxorting a W3 example SVG too, but got the same error message.

```svg
<svg height="30" width="200">
  <text x="0" y="15" fill="red">I love SVG!</text>
  Sorry, your browser does not support inline SVG.
</svg>
```
