### ISSUE TITLE
[previewer] SVG previewer with pixelgrid overlay

### ISSUE THREAD

**Issue by ericfennis** [lishu/vscode-svg2#39]
I like this extension, I use this often to optimize some svg code.
For this I use the previewer, what I currently miss is an pixel-grid overlay. So I can see if svg elements still aligned pixel-perfect.

### Toggle button for the grid.
![image](https://user-images.githubusercontent.com/11825403/92106217-5ace0900-ede4-11ea-98a5-a2bb86bd2c80.png)

### Pixel grid used in other applications (like figma).
_Little gray lines overlaying the image_ 
![image](https://user-images.githubusercontent.com/11825403/92106043-0f1b5f80-ede4-11ea-8f9b-9dfc1b9c41b4.png)

**Comment by lishu** [comment]
❤Thank for your feedback.
Try new Version.

**Comment by ericfennis** [comment]
@lishu Nice work, this is awesome!
