### ISSUE TITLE
Minify doesn't work in all cases

### ISSUE THREAD

**Issue by webjay** [lishu/vscode-svg2#4]
This is the original:

    <?xml version="1.0" encoding="UTF-8"?>
    <svg width="123px" height="140px" viewBox="0 0 123 140" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        
        <title>round_base</title>
        <desc>Created with Sketch.</desc>
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="base" stroke="#FFFFFF" stroke-width="0.5">
                <polygon id="Path" points="121.5 35.71 61.5050314 1.29 1.5 35.71 1.5 104.56 61.5050314 138.99 121.5 104.56"></polygon>
                <path d="M61.5,70.14 L61.5,138.99" id="Path"></path>
                <path d="M121.5,35.71 L61.88,70.14" id="Path"></path>
                <path d="M15.98,43.55 L75.26,8.92" id="Path"></path>
                <path d="M30.71,52.28 L89.98,17.65" id="Path"></path>
                <path d="M46.25,61.18 L105.52,26.55" id="Path"></path>
                <path d="M15.5,43.55 L15.5,112.22" id="Path"></path>
                <path d="M30.5,52.28 L30.5,121.01" id="Path"></path>
                <path d="M46.5,61.18 L46.5,129.97" id="Path"></path>
                <path d="M75.5,8.92 L75.5,77.88" id="Path"></path>
                <path d="M89.5,17.65 L89.5,86.15" id="Path"></path>
                <path d="M105.5,26.55 L105.5,95.58" id="Path"></path>
                <path d="M15.5311104,112.503746 L75.6856773,77.6334116 L15.5311104,112.503746 Z" id="Path"></path>
                <path d="M89.0773613,85.7552798 L30.7100004,121.01" id="Path"></path>
                <path d="M46.25,129.97 L105.52,95.58" id="Path"></path>
                <path d="M2.25,35.71 L121.134452,104.499175" id="Path"></path>
            </g>
        </g>
    </svg>

and this is when it is compressed:

    <svg width="123" height="140"><g stroke="#FFF" stroke-width=".5" fill="none" fill-rule="evenodd"><path d="M121.5 35.71L61.505 1.29 1.5 35.71v68.85l60.005 34.43 59.995-34.43zM61.5 70.14v68.85M121.5 35.71L61.88 70.14M15.98 43.55L75.26 8.92M30.71 52.28l59.27-34.63M46.25 61.18l59.27-34.63M15.5 43.55v68.67M30.5 52.28v68.73M46.5 61.18v68.79M75.5 8.92v68.96M89.5 17.65v68.5M105.5 26.55v69.03"/><path d="M15.531 112.504l60.155-34.87-60.155 34.87zM89.077 85.755L30.71 121.01M46.25 129.97l59.27-34.39M2.25 35.71l118.884 68.79"/></g></svg>

which doesn't seem to work.

This works:

    <?xml version="1.0" encoding="UTF-8"?>
    <svg width="1022px" height="171px" viewBox="0 0 1022 171" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        
        <title>Group 3</title>
        <desc>Created with Sketch.</desc>
        <defs>
            <polygon id="path-1" points="0 0.00033 1021.84478 0.00033 1021.84478 170.6529 0 170.6529"></polygon>
        </defs>
        <g id="Desktop" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Splash" transform="translate(-209.000000, -427.000000)">
                <g id="Group-3" transform="translate(209.000000, 427.000000)">
                    <mask id="mask-2" fill="white">
                        <use xlink:href="#path-1"></use>
                    </mask>
                    <g id="Clip-2"></g>
                    <path d="M-0.00022,168.55223 L33.38368,168.55223 L44.82258,96.41533 L79.13928,96.41533 L67.70038,168.55223 L101.31748,168.55223 L127.69768,2.10133 L94.08058,2.10133 L84.27628,64.43283 L49.72528,64.43283 L59.76388,2.10133 L26.37998,2.10133 L-0.00022,168.55223 Z M136.28648,168.55223 L207.95588,168.55223 L213.09178,136.56863 L174.10558,136.56863 L180.17538,99.21703 L214.49318,99.21703 L219.39478,67.23343 L185.07698,67.23343 L190.68038,32.68243 L229.66768,32.68243 L234.33608,2.10133 L162.66668,2.10133 L136.28648,168.55223 Z M226.98038,168.55223 L260.82958,168.55223 L269.93538,140.06993 L308.45408,140.06993 L309.15478,168.55223 L342.77078,168.55223 L332.49898,2.10133 L285.57628,2.10133 L226.98038,168.55223 Z M278.57258,112.52263 L298.88188,49.02403 C301.68358,39.92043 304.25208,31.28213 306.35308,23.11133 C306.11988,27.08123 306.11988,30.58143 306.11988,34.08383 C306.11988,35.25093 306.11988,40.38683 306.35308,49.25833 L307.75338,112.52263 L278.57258,112.52263 Z M362.05158,168.55223 L389.13138,168.55223 C415.27838,168.55223 434.42168,167.85153 452.39788,149.40893 C468.73948,132.83303 480.64478,101.08373 480.64478,65.59993 C480.64478,22.17853 459.86798,2.10133 415.74588,2.10133 L388.43178,2.10133 L362.05158,168.55223 Z M400.10388,137.96893 L416.91298,32.68243 L419.01398,32.68243 C439.09008,32.68243 447.26198,42.72213 447.26198,66.53273 C447.26198,110.42273 429.75328,138.20323 403.60628,138.20323 C402.43918,138.20323 401.27098,137.96893 400.10388,137.96893 L400.10388,137.96893 Z M494.25178,168.55223 L563.11948,168.55223 L568.02218,136.56863 L532.77158,136.56863 L554.01588,2.10133 L520.63088,2.10133 L494.25178,168.55223 Z M617.11628,168.55223 L643.49648,2.10133 L609.64508,2.10133 L583.26598,168.55223 L617.11628,168.55223 Z M711.54688,104.35293 L735.12428,104.35293 C732.79008,127.46393 723.45218,139.60463 709.44588,139.60463 C696.83988,139.60463 690.53578,130.73203 690.53578,113.45653 C690.53578,91.27943 694.73888,69.80193 701.27508,52.52643 C706.64418,38.75223 714.11428,31.74853 724.15288,31.74853 C734.42468,31.74853 740.49448,38.28583 742.59548,51.35933 L776.91328,39.68723 C768.27498,12.60523 752.39978,0.00033 726.48708,0.00033 C705.24278,0.00033 687.96728,9.80573 677.46228,27.31443 C664.62308,48.55763 656.21798,78.90663 656.21798,108.78813 C656.21798,149.64213 673.72778,170.65323 706.87738,170.65323 C748.43208,170.65323 768.04178,139.60463 774.11158,74.00393 L716.21528,74.00393 L711.54688,104.35293 Z M787.90558,168.55223 L821.28838,168.55223 L832.72728,96.41533 L867.04508,96.41533 L855.60618,168.55223 L889.22328,168.55223 L915.60348,2.10133 L881.98528,2.10133 L872.18098,64.43283 L837.62998,64.43283 L847.66858,2.10133 L814.28468,2.10133 L787.90558,168.55223 Z M935.70048,168.55223 L969.31868,168.55223 L990.56188,33.61743 L1016.94208,33.61743 L1021.84478,2.10133 L936.63438,2.10133 L931.49848,33.61743 L957.17908,33.61743 L935.70048,168.55223 Z" id="Fill-1" fill="#1029B9" mask="url(#mask-2)"></path>
                </g>
            </g>
        </g>
    </svg>

compressed:

    <svg viewBox="0 0 62 11"><path d="M0 10.113h2.003l.686-4.328h2.06l-.687 4.328h2.017L7.662.126H5.645l-.588 3.74H2.984l.602-3.74H1.583L0 10.113zm8.177 0h4.3l.309-1.919h-2.34l.365-2.241h2.059l.294-1.919h-2.06l.337-2.073h2.34l.28-1.835H9.76l-1.583 9.987zm5.442 0h2.03l.547-1.709h2.311l.042 1.71h2.017L19.95.125h-2.815l-3.516 9.987zm3.095-3.362l1.219-3.81c.168-.546.322-1.064.448-1.554-.014.238-.014.448-.014.658 0 .07 0 .378.014.91l.084 3.796h-1.75zm5.01 3.362h1.624c1.569 0 2.717-.042 3.796-1.148.98-.995 1.695-2.9 1.695-5.029 0-2.605-1.247-3.81-3.894-3.81h-1.64l-1.582 9.987zm2.282-1.835l1.009-6.317h.126c1.204 0 1.695.602 1.695 2.031 0 2.633-1.05 4.3-2.62 4.3-.07 0-.14-.014-.21-.014zm5.65 1.835h4.131l.294-1.919h-2.115L33.241.126h-2.003l-1.583 9.987zm7.371 0L38.61.126h-2.031l-1.583 9.987h2.031zm5.666-3.852h1.414c-.14 1.387-.7 2.115-1.54 2.115-.757 0-1.135-.532-1.135-1.569 0-1.33.252-2.619.645-3.655.322-.827.77-1.247 1.372-1.247.616 0 .98.392 1.107 1.177l2.059-.7C46.096.755 45.144 0 43.589 0c-1.274 0-2.311.588-2.941 1.639-.77 1.274-1.275 3.095-1.275 4.888 0 2.452 1.05 3.712 3.04 3.712 2.493 0 3.67-1.863 4.034-5.799h-3.474l-.28 1.821zm4.581 3.852h2.003l.687-4.328h2.059l-.687 4.328h2.017L54.936.126H52.92l-.588 3.74h-2.073l.602-3.74h-2.003l-1.583 9.987zm8.868 0h2.017l1.275-8.096h1.583l.294-1.89h-5.113l-.308 1.89h1.54l-1.288 8.096z"/></svg>

**Comment by lishu** [comment]
This see not about svg content bug, only in `Untitled` file, If fix no right, please open a new issue.
