### ISSUE TITLE
Is there a way to modify code colouring ?

### ISSUE THREAD

**Issue by wiredogDesign** [lishu/vscode-svg2#41]
<img width="390" alt="Screen Shot 2020-09-17 at 22 44 34" src="https://user-images.githubusercontent.com/42998685/93531747-a5e53180-f937-11ea-8ed9-54f4d0b8475d.png">

Code is hard to read with this colour formatting, and changing themes makes no difference. Otherwise, this is a great extension

**Comment by lishu** [comment]
See about #3

**Comment by onirix** [comment]
I just turn off syntax highlighting for the same reason than @wiredogDesign.
I think it could be preferable to make these colors editable.
Could be useful to distinguish numbers values from commands letters especially.

Thanks for the work !
