### ISSUE TITLE
emmet support

### ISSUE THREAD

**Issue by tjx666** [lishu/vscode-svg2#42]
By using following setting, I can get emmet suggestion, but can't get svg specific tag suggestion
```
"emmet.includeLanguages": {
        "svg": "html"
 },
```

![screenshot_2020-09-20_00-53-39](https://user-images.githubusercontent.com/41773861/93672233-d2d24980-fadb-11ea-9917-dc19ffc8fe39.png)
![screenshot_2020-09-20_00-54-01](https://user-images.githubusercontent.com/41773861/93672236-d534a380-fadb-11ea-82af-3cba5e333c96.png)

**Comment by lishu** [comment]
`emmet` see is not extensible for other extension. So this is base Microsoft build-in features.
