### ISSUE TITLE
Implemen Emmet-style autocomplete

### ISSUE THREAD

**Issue by proimage** [lishu/vscode-svg2#43]
When editing a `.svg` file, I can't seem to get autocompletion to trigger. It always says "No suggestions". Presumably it's some setting I have that's interfering with things, but I can't for the life of me figure out which one.

How can I get SVG autocomplete to work again?

**Comment by lishu** [comment]
Because you don't provide additional information available, there are only some common solutions available here.

1. Reinstall SVG(jock.svg) extensions.

2. Try open your vscode setting file `settings.json` search all `svg` see if has any overwrite setting, or backup this file and delete all `svg` word showed options.

**Comment by proimage** [comment]
Yeah, sorry I didn't give more information, I just honestly didn't know what else to give.

My user settings.json has no mentions of svg anywhere.

I have uninstalled the extension and reinstalled it, with no change.

Here's the list of extensions I have installed:

![image](https://user-images.githubusercontent.com/1027523/95076717-f8d22d80-071a-11eb-9f3c-7ff95c2f11ec.png)

**Comment by lishu** [comment]
I see that you have installed a `Remote` extension. Currently, the `SVG` extension may not work properly in remote mode.

Is `SVG` language mode info show in your status bar right side? Try click it see what Association the `SVG`.
![43](https://user-images.githubusercontent.com/1331008/95182046-aebe7a00-07f6-11eb-8c67-091f94780e15.png)

**Comment by proimage** [comment]
I think I found the problem.

I have been used to using Emmet abbreviations to autocomplete HTML tags. Type `ul` and get `<ul></ul>`, etc. But this SVG extension doesn't seem to use Emmet-style autocomplete triggers. It requires a less-than symbol to come first: type `<path` and the autocomplete appears.

So that's one aspect of the problem resolved. However, it leads to a sub-problem: there is no SVG tag autocomplete when inside the context of an HTML document.

Can the SVG autocomplete be marked as some sort of subset of HTML, just like typing inside `<style>...</style>` tags gets CSS autocomplete instead of HTML?

**Comment by lishu** [comment]
The Emmet-style autocomplete trigger is not supported for now.
Why? Because I didn't implemented it. 😅 
This behavior needs to be implemented entirely on its own outside of HTML/CSS, so I'll plan to do it, but it won't be quick.

**Comment by proimage** [comment]
Yay!

Would it make more sense for Emmet to include SVG tags in its lineup of completions?

**Comment by lishu** [comment]
Try 1.3.11 version.
😂 Sorry for the delay.
Because of some conflicts, I rewritten the entire auto-completion feature. It is important to note that there is no complete implementation of all emmet 2 features and must be used within at least one root element.

**Comment by lishu** [comment]
Full Emmet 2.0 style autocomplete has added in 1.3.12.
