### ISSUE TITLE
provide ruler and cross line in preview page

### ISSUE THREAD

**Issue by tjx666** [lishu/vscode-svg2#44]
ruler:

![screenshot_2020-10-20_23-24-51](https://user-images.githubusercontent.com/41773861/96608381-e4ea1680-132b-11eb-8088-5b121ae67f6c.png)

cross line: 

![screenshot_2020-10-20_23-27-42](https://user-images.githubusercontent.com/41773861/96608406-eca9bb00-132b-11eb-82e9-f9531eed4bfd.png)

Remarks: The crosshairs above is a chrome extension function, not chrome dvetools comes with

**Comment by lishu** [comment]
cross line 是什么东西？像 Photoshop 一样从标尺上自己拉出来的辅助线？

**Comment by tjx666** [comment]
十字交叉线 @lishu

**Comment by lishu** [comment]
哦，是提示鼠标所在位置的的吧。😯

**Comment by lishu** [comment]
版本1.4.0, 试试吧😘

**Comment by tjx666** [comment]
> 版本1.4.0, 试试吧😘

试了下，很棒哦!
