### ISSUE TITLE
Please add brace formatting options for CSS part within SVG file

### ISSUE THREAD

**Issue by SetTrend** [lishu/vscode-svg2#46]
Currently, when auto-formatting code (e.g. by pressing `SHIFT`+`ALT`+`F` on the keyboard) vscode-svg2 formats CSS areas with opening brackets at the end of a previous line:

```css
rect {
}
```

Please, add a new option to your extension to allow for putting opening braces to new lines, like this:

```css
rect
{
}
```

In VS Code, the corresponding setting (e.g. for JavaScript) is found here:
`"javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,`

**Comment by lishu** [comment]
Current SVG2 use HTML language server do formating.
It will load your `html.format`  for base setting. If it can not do your want, I do think has other easy way.

**Comment by lishu** [comment]
You can set up other formatters for SVG files that support the functions you need
