### ISSUE TITLE
Please automatically add xlink namespace

### ISSUE THREAD

**Issue by SetTrend** [lishu/vscode-svg2#47]
When using the `use` element, trying to reference an object from a `defs` section, I suggest to automatically add the `xlink` namespace to the corresponding anchestor `svg` element if there is no corresponding namespace available to (valid for) the current element:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-100 -100 400 500"
     xmlns:xlink="http://www.w3.org/1999/xlink">
```

Perhaps this may come with an option in Settings, having the user determine a preferred element to add the namespace to:

- **parent** - the immediate parent element
- **svg** - the immediate anchestor `svg` element
- **root** - the root element of the current file (this is usually an `svg` element)

**Comment by lishu** [comment]
`xlink` see is a **deprecated** feature. and `use`/`href` see not required it.
Is there any special reason to need it?

**Comment by SetTrend** [comment]
Er ... D'oh ... Yes, you are perfectly right. My information was a leftover from the SVG 1.1.
