### ISSUE TITLE
IntelliSense for 'animateTransform' 'type' attribute is not correct

### ISSUE THREAD

**Issue by SetTrend** [lishu/vscode-svg2#50]
Currently, the suggestions for the `animateTransform` element's `type` attribute seem incorrect:

![animateTransform](https://user-images.githubusercontent.com/9283914/97809448-2dc79680-1c6d-11eb-8efd-30acd7c49f87.png)

The SVG Animations spec lists the following values for the above mentioned attribute:

https://svgwg.org/specs/animations/#AnimateTransformElementTypeAttribute

**Comment by lishu** [comment]
I'm sorry to have this problem. This is due to the recent rewriting of Emmet style support, which will be updated later.

**Comment by SetTrend** [comment]
Thank you for your quick reaction!
