### ISSUE TITLE
This extension cause html file can't use class autocomplete

### ISSUE THREAD

**Issue by tjx666** [lishu/vscode-svg2#51]
@lishu  When I disable this extension I can use the html autocomplete.

![screenshot_2020-12-10_23-57-04](https://user-images.githubusercontent.com/41773861/101795966-6d727f80-3b43-11eb-9809-e77ccd670457.png)

Can't when enable it:

![screenshot_2020-12-10_23-58-14](https://user-images.githubusercontent.com/41773861/101796125-95fa7980-3b43-11eb-8c91-a1e31061bfab.png)

Version Info:

```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
This Extension: V1.4.1
```

HTML Language Server Output log:

![screenshot_2020-12-10_23-59-59](https://user-images.githubusercontent.com/41773861/101796412-db1eab80-3b43-11eb-8fe8-914dae16e872.png)

Language SVG Server Output Log:

![screenshot_2020-12-11_00-00-51](https://user-images.githubusercontent.com/41773861/101796587-03a6a580-3b44-11eb-8734-1067f3082e23.png)

**Comment by lishu** [comment]
知道了哦~~这个问题似乎是我想为 html 附加 svg 元素造成的，官方的文档事实上没有把附加数据要求的必要了属性关系写出来，然后我就嗯，失误了，抱歉。
