### ISSUE TITLE
Embeded image not found

### ISSUE THREAD

**Issue by linsui** [lishu/vscode-svg2#53]
`image` with a href is not displayed.

**Comment by lishu** [comment]
The previewer is **Directly** through `WebView`
If something not displayed, Then it will probably not be displayed correctly in the browser of the same kernel

I known is a browser kernel limit, but Render completely by yourself if too much for a extensions. You should probably use a more professional svg authoring tool like `Inkscape`.

**Comment by lishu** [comment]
There is also a possibility that the security restrictions of the WebView Api cause the referenced path resource to fail to load, and naturally it cannot be displayed correctly.

**Comment by linsui** [comment]
Thanks! I guess it's a path restriction. Online images can be displayed correctly but local images can't be loaded.
