### ISSUE TITLE
VS Code Minify SVG keybinding

### ISSUE THREAD

**Issue by FatehAK** [lishu/vscode-svg2#57]
I tried to add a keybinding to the `Minify SVG` command. But it doesn't seem to show up in the VS Code Keyboard shortcuts screen. Is it possible to assign a keybinding to this command?

**Comment by lishu** [comment]
`Minify SVG` command is a context command, Is in `EXPLORER` and in `.svg` document has diff effect, so is not see in `Keyboard Shortcuts`. but you can access it just in context menu.
