### ISSUE TITLE
Controls are very small

### ISSUE THREAD

**Issue by septatrix** [lishu/vscode-svg2#58]
![image](https://user-images.githubusercontent.com/24257556/104848976-b0b0d280-58e7-11eb-887b-8addf1801e10.png)

The title in the tab has a normal size which is very readable. The elements inside the webview however are rather small (at least on a 1440p monitor).

**Comment by lishu** [comment]
This is the design, Because it will not change (add, remove, reorder)，You should get used to it soon.

**Comment by septatrix** [comment]
Okay but you should recognize that they are barely readable.

And as they are based on a fixed font size (10px by the looks of it) they are also not accessible to users who use a larger font size because of vision deficiencies. Lighthouse and WAVE recommend a font size of 16px for normal text. Using a larger font size (like exposed in `--vscode-font-size`) would not hurt. The saved screen space would only be a few pixels...

**Comment by lishu** [comment]
There's a bit of a dilemma between design and usability.
Toolbar size settings will be added in future updates.
This issue will be turned off after the feature update is included.

Thank you for your continued support.

**Comment by septatrix** [comment]
What benefit or design advantage does an unreadable interface yield beside detering new users? I do not want to sound rude (even though I probably do) but the only reasonable thing IMO would be to copy the default IDE font size. If a user wants a small font size they probably prefer it throughout the whole interface. Should you choose to make this configurable I would encourage you to just set the default on the toolbar to be 1em an set the font-size on the body to the one exposed by VSCode.

If there are any specific design reasons however why you choose such small sizes I would be interested to know as I do a bit of interface/UX design. Saving a few pixels of vertical space (and therefore also making the buttons hard to click) however does not occur as a valid reason to me...

**Comment by lishu** [comment]
It can be said that from a user experience perspective and all industry standards, what you said is correct.
But after all, this is just a free extension developed by personal hobby, and it is inevitable that there are some personal preference choices.
