### ISSUE TITLE
how to format SVG

### ISSUE THREAD

**Issue by numanzahid** [lishu/vscode-svg2#60]
Extension description says it can format SVG using SVGO but I am unable to format SVG. I can minify the SVG alright but I can't find the option to prettify the SVG. There is not formatting option in command list either. 

Please let me know how to do formatting in vs code.

thanks.

**Comment by lishu** [comment]
Formatting is ide invoke, Just `Format Document` (Shift + Alt + F) or Select it in document context menu will do it.

**Comment by numanzahid** [comment]
I have tried ide invoked formatting multiple times, but it is not working.

**Comment by lishu** [comment]
Maybe some other extension override this action, I can not confirm that.
Are your should you use this extension? (Name: SVG, id: jock.svg)

**Comment by numanzahid** [comment]
it is your extension I am sure.
https://snipboard.io/ofPglC.jpg

I have prettier installed. it was blocking formatting. 

```
"[svg]": {
    "editor.defaultFormatter": "jock.svg"
  }
```
this worked.

thanks for your help.

**Comment by lishu** [comment]
Because SVGO is not suitable for complex SVG content , so it replace by use html language service in earlier versions, It will handle better but it doesn't change the code significantly.
