### ISSUE TITLE
Are xlink hrefs supposed to be clickable?

### ISSUE THREAD

**Issue by moio** [lishu/vscode-svg2#61]
:wave: authors!

I was wondering whether xlink hrefs are supposed to work - I am working on an SVG created via Graphviz and it would be useful to navigate them. Example:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="199pt" height="44pt"
 viewBox="0.00 0.00 199.08 44.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 40)">
<title>battleplan</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-40 195.083,-40 195.083,4 -4,4"/>
<g id="node1" class="node">
<title>consoleless</title>
<g id="a_node1"><a xlink:href="consoleless.md" xlink:title="Console&#45;less operation">
<ellipse fill="none" stroke="#000000" cx="95.5415" cy="-18" rx="95.5831" ry="18"/>
<text text-anchor="middle" x="95.5415" y="-14.3" font-family="Times,serif" font-size="14.00" fill="#000000">Console&#45;less operation</text>
</a>
</g>
</g>
</g>
</svg>
```

Thanks in advance!

**Comment by lishu** [comment]
If `navigate them` is in mean in code:
This doesn't seem to be a necessary feature for SVG files.
And I can't know if the link is a file (type) that can be opened by a local vscode.
At the same time, these checks may use too much IO resources.

If `navigate them` is in mean browser(preview)
Preview is in limit by vscode api Security. It can not easy do that.

**Comment by moio** [comment]
> If navigate them is in mean browser(preview)

In my view, such links should work as links in the markdown preview pane - if they point to a local file (eg. `[click me](another_local_file.md)`), then it opens in VSCode. If it's an http link, it should open a browser window (possibly after a popup).

Does that make sense to you?

**Comment by lishu** [comment]
I know what you mean now.
But this is not easy task (even very complicated) & not necessary to preview SVG.
