### ISSUE TITLE
Prevent removing viewBox on minify

### ISSUE THREAD

**Issue by ronilaukkarinen** [lishu/vscode-svg2#66]
viewBox attribute always gets removed on minify. How to force to retain it?

**Comment by lishu** [comment]
Try check your settings.
Input `svg viewbox` in your setting search box, check if any things not expected.
![image](https://user-images.githubusercontent.com/1331008/114332244-694d8180-9b78-11eb-8dea-401abd996bc6.png)

**Comment by ronilaukkarinen** [comment]
Oh right, didn't see that. Thanks & sorry!
