### ISSUE TITLE
option to not remove linebreak

### ISSUE THREAD

**Issue by PubliAlex** [lishu/vscode-svg2#67]
Hello,

This extension is perfect, there is just one thing that is really annoying to me.

When I minify a SVG, I want to keep the line break to keep svg readable.

Is it possible to add an option "remove linebreak on / off" or add a new action "prettify" in addition of minify ?

Thank you

**Comment by lishu** [comment]
The `minify` is base SVGO implement. Also option is limit by it.
I'm sorry I didn't find any option is use for your issues.
Search 'svg minify' in your settings can get you all option can be changed.

**Comment by alexandertrimble** [comment]
I have changed every single svg.minify option available and it is still auto-deleting linebreaks on save. Please remove this feature, or turn it off by default.

**Comment by lishu** [comment]
I'm sorry to waste your time, as I said above, SVGO itself does not support features I can not immediately support.
At the same time, you need to understand that minimizing this feature is not intended for readability in itself, and its first action is to remove unnecessary spaces.
