### ISSUE TITLE
activationEvents : * -> onLanguage:svg

### ISSUE THREAD

**Issue by tjx666** [lishu/vscode-svg2#68]
This would speed up  startup of VSCode and save resource when not deal with svg file.

**Comment by lishu** [comment]
这个我知道啊，早期是这样的，但是这个扩展已经出了 4 年了，一些慢慢累加的新的小功能如果只使用 onLanguage:svg 就会无法使用啊

**Comment by tjx666** [comment]
@lishu 比如说？VSCode 的扩展的激活方式还是很灵活的？

**Comment by lishu** [comment]
主要是测试所有功能可用性会比较花时间，而且我自己记性也不是特别好，可能测试一次下来只会试到 80% 左右的功能。
= = 并不是所有的小功能都在 readme 里写了。
饿，懒这件事我是打死也不会认的。毕竟这是个完全没有赞助的项目。🤣

**Comment by lishu** [comment]
非常杯具，我已经改动，确没能发布，因为无法打包了，整个 vscode 插件编译打包体系有了变化，这得试一回了，下一个更新会解决此问题。
