### ISSUE TITLE
Please add support for bulk minify svg

### ISSUE THREAD

**Issue by GorvGoyl** [lishu/vscode-svg2#75]
Is there a way I can right click on a folder and select Minify SVG and it'd minify all SVGs inside that folder. Moreover, Similar behavior if I multi-select some SVG files and it minifies all of them. Right now it's tedious to minify one-by-one.

**Comment by lishu** [comment]
Bulk minify is more like `build` action, your should try use `svgo` command line tool or other in build time tool plugin for this target.
