### ISSUE TITLE
Use codicons in Theme Icon API

### ISSUE THREAD

**Issue by 4086606** [lishu/vscode-svg2#77]
Since this extension was published, there is now [`ThemeIcon`](https://code.visualstudio.com/api/references/vscode-api#ThemeIcon) and `$(icon)` syntax so use native codicons in extension?

**Comment by lishu** [comment]
I don't known what is your need.
They syntax your describe is not part of `SVG`

**Comment by lishu** [comment]
I don't known what is your need.
What you describe is not part of `SVG`

**Comment by 4086606** [comment]
It's a suggestion for extension itself. The need is for better accessibility

**Comment by lishu** [comment]
Thank you for your suggestion, but the larger of this extended release package is not icons, most of which are SVG format.
Resources that are not used will be removed in future releases.

**Comment by 4086606** [comment]
Should I open PR to collect this work in one place?
