### ISSUE TITLE
Failed to format the document. TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by BuZZ-dEE** [lishu/vscode-svg2#8]
https://github.com/BuZZ-dEE/fegram/blob/268f44ac6c4b2cc0f432d3a2f4af01ab2b1a35d6/fegram.svg?short_path=18779db

**Comment by lishu** [comment]
This issues is `svgo` has some error handle comments in `<defs>`.
Reference issue in https://github.com/svg/svgo/issues/1221

**Comment by lishu** [comment]
The SVGO author doesn't seem to be responding in a timely.
This project will make private changes to the SVGO package
