### ISSUE TITLE
Writing self closing tags

### ISSUE THREAD

**Issue by finnhvman** [lishu/vscode-svg2#82]
Great plugin overall!

I'm tinkering a lot with filter effects (feTurbulence, feColorMatrix, etc.) and most of these would be better self-closed.

So right now the auto-completion produces something like this:
```svg
<feTurbulence>

</feTurbulence>
```

But instead, I would much rather have something like this:
```svg
<feTurbulence [...]
```

Then I write my attributes and smart-close by typing a slash.

Maybe this is already possible, I'm just not aware of it?

**Comment by lishu** [comment]
The new version has a `Simple Elements` configuration will help you.
![image](https://user-images.githubusercontent.com/1331008/126020930-39711796-b6f6-4428-b9e5-855c562e1d47.png)

**Comment by finnhvman** [comment]
Wow, thank you! It works!
