### ISSUE TITLE
Prettify not working

### ISSUE THREAD

**Issue by aabanaag** [lishu/vscode-svg2#87]
I installed the plugin but viewing SVG files doesn't apply the prettify

I already have a prettier plugin installed and configured formatOnSave to true but not sure if that is what is causing it. Other features such as preview seem to be working properly.

![Screen Shot 2021-08-18 at 3 36 55 PM](https://user-images.githubusercontent.com/2245822/129857425-37a9d02d-f845-4448-892d-074a5674b6d3.png)

**Comment by lishu** [comment]
Other plugin like `prettier` maybe override format action, you need add vscode settings.
```json
"[svg]": {
  "editor.defaultFormatter": "jock.svg"
}
```

**Comment by aabanaag** [comment]
I applied this but still the same

**Comment by aabanaag** [comment]
oh nevermind it worked. I have formatOnSave enabled then I triggered the save and it worked perfectly. thank you!
