### ISSUE TITLE
Option to disable preview extensions

### ISSUE THREAD

**Issue by SNDST00M** [lishu/vscode-svg2#88]
Letting us use the extension with the preview extensions disabled:
- I want to use this extension with a different previewer
- Maybe some people want to use the extension for syntax only

**Comment by lishu** [comment]
The preview is only a command add to context menu and document tool, is not disable other thing. your can use other preview without problem.

**Comment by SNDST00M** [comment]
But I have two SVG preview action buttons in the editor.

**Comment by lishu** [comment]
This button define is in define document, can not dynamic change in code.

**Comment by SNDST00M** [comment]
I think there should be a way to switch them off using [`setContext`](https://github.com/microsoft/vscode/blob/1.60.1/extensions/image-preview/src/preview.ts#L60) and `onDidChangeConfiguration`

**Comment by SNDST00M** [comment]
Would you like PR for this?

**Comment by lishu** [comment]
I'll check it, So what previewer features is you need?

**Comment by SNDST00M** [comment]
`_svg.showSvg`, `_svg.showSvgByUri` & `_svg.showAllSvg` all need optional disable

**Comment by lishu** [comment]
Thanks for the Example.
BTW, I just want known how improvement my previewer.

**Comment by SNDST00M** [comment]
Images with a set height and width could be centered. The default image background should look native to VSC:

![image](https://user-images.githubusercontent.com/82655227/133595909-305051ea-b7bb-490c-9302-30bbae6999c2.png)

> Styling: https://github.com/microsoft/vscode/blob/1.60.1/extensions/image-preview/media/main.css

There should also be a improved support for SVGs with reflow:

![image](https://user-images.githubusercontent.com/82655227/133597552-7779694d-4e1a-45a4-bbc6-02c68c2b366a.png)
