### ISSUE TITLE
Pixel grid is broken

### ISSUE THREAD

**Issue by ericfennis** [lishu/vscode-svg2#92]
Zooming to pixel level breaks layout see picture.
![image](https://user-images.githubusercontent.com/11825403/137502763-0c4bf1a6-9ab6-4089-b074-0527c0243fd7.png)

I'm designing icon on 24x24 pixel grid and would be nice if the steps to zoom in are a bit smaller.
now it goes from 100% to 200%, 400% 800% 1600%.
The steps 400%, 800% 1600% are really big steps to work with, would be nice if there are some steps in between.

And would be nice if there is an option that the ui memorises the zoom level (maybe a default option or something), each time opening new file I need to zoom in again.

**Comment by lishu** [comment]
Processing...
BTW, Preivew support  Ctrl/Meta + Mouse Wheel  for fast zoom in/out.
