### ISSUE TITLE
Change scope name to text.xml.svg

### ISSUE THREAD

**Issue by caleb531** [lishu/vscode-svg2#93]
I came from Atom and had the [language-svg](https://atom.io/packages/language-svg) package installed. That package uses `text.xml.svg` for the scope name, which is great because SVG is technically XML. It also made sure that all of my `text.xml` snippets could also be used in the SVG language mode.

I was wondering if you might consider changing the `text.svg` scope for this extension's language mode to `text.xml.svg`. That way, customizations which use the `text.xml` scope will also apply to SVG files.

This is similar to how the Handlebars language mode in VS Code (`text.html.handlebars`) inherits from the `text.html` scope.

**Comment by lishu** [comment]
Add at V 1.4.14
