### ISSUE TITLE
Sometimes preview bugs out and won't let you edit code

### ISSUE THREAD

**Issue by sandorex** [lishu/vscode-svg2#99]
When i try to move the preview it bugs out and doesn't let me open the original svg file anymore, when i click on it's tab it goes back to the preview
This continues until i close the preview

(terrible video showing the issue)
https://youtu.be/O1VR1nBhpDs

<details>

Extension Version: v1.4.14
Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

</details>

**Comment by lishu** [comment]
Try new version, preview is design in diff side & show always, back it is not mean, try not do that.
